version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  api:
    build:
      context: ./ex1/contratosAPI
      dockerfile: DockerFile
    container_name: api
    restart: always
    ports:
      - "16000:16000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb/contratos

  frontend:
    build:
      context: ./ex2/contratos
      dockerfile: DockerFile
    container_name: frontend
    restart: always
    ports:
      - "16001:16001"
    depends_on:
      - api